FROM python:3.9.18-slim-bullseye
WORKDIR /app
COPY ./ /app/
RUN pip install --no-cache-dir -r requirements.txt
ENV TELEGRAM_BOT_API_KEY="7388383391:AAEQoOAHVQiU8XtBcKH2qEv2Slwr8k-UQpU"
ENV GEMINI_API_KEYS=" AIzaSyCzCdZUrHBtTjlj8yPB_K1LRC5wPB-CY9c"
CMD ["sh", "-c", "python main.py ${TELEGRAM_BOT_API_KEY} ${GEMINI_API_KEYS}"]
